server:
  port: 8080
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/views
          suffix: .html
mybatis-plus:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.yuanjun.mybatis.entity
